### ISSUE TITLE
The dotnet command running path is not specified

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/orleans-url-shortener#3]
### Description

**Describe the issue:**
Running the command `dotnet add package` and there is an error: "The project was not found."

![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/138087452/63928c61-e003-4c5c-8d99-64f428ca8a8f)

**Suggestion:**
Add command `cd src/web` before `dotnet add package Azure.Identity `.

@seesharprun and @hemarina for notification.

### Repro steps

None

### Expected behavior

Execute  commands successful.

**Comment by seesharprun** [comment]
This has been resolved in PR #4
